name: fleet
type: go

minimum_dependency_age:
  enforce: false

up:
  - go: 1.26.5
  - node:
      version: v24.10.0
      yarn: v1.22.22
  - podman

commands:
  style:
    desc: Run Go linters
    run: make lint-go
  test:
    desc: Run Go tests
    run: make test-go
